site_name: Lecture Notes Old School
site_description: Direct links to compiled lecture-note PDFs.
site_url: https://nowitends.github.io/Writing/
repo_url: https://github.com/nowitends/Writing
repo_name: nowitends/Writing

theme:
  name: mkdocs

nav:
  - Lecture PDFs: index.md

